version: '3.8'

services:
  code-server:
    build: .
    ports:
      - "2323:2323"
    environment:
      - PASSWORD=pass1234
    volumes:
      - ./workspace:/home/coder/project
      - ./certs:/home/coder/certs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
